// ignore_for_file: type=lint
// THIS FILE WAS AUTOMATICALLY GENERATED BY RIVE_GENERATOR. MODIFICATIONS WILL BE LOST WHEN THE GENERATOR RUNS AGAIN.
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:rive/rive.dart' as rive;
import 'package:rive/src/rive_core/state_machine_controller.dart' as core;

const assetsBaseFolder = "assets";

class Valybol {
  final rive.RiveFile file;
  static String get assetPath {
    return (kIsWeb ? '' : assetsBaseFolder + '/') + 'valybol.riv';
  }

  Valybol._(this.file);

  static Future<Valybol> load() async {
    final riveFile =
        rive.RiveFile.import(await rootBundle.load(Valybol.assetPath));
    return Valybol._(riveFile);
  }

  Beach? _beach;
  Beach get beach => _beach ??= Beach(file.artboardByName(r'Beach')!);

  Whale? _whale;
  Whale get whale => _whale ??= Whale(file.artboardByName(r'whale')!);
}

class Beach {
  final rive.Artboard artboard;
  Beach(this.artboard);

  final animations = const BeachAnimations();

  BeachStateMachine1StateMachine getBeachStateMachine1StateMachine(
      [core.OnStateChange? onStateChange]) {
    return BeachStateMachine1StateMachine(this
        .artboard
        .stateMachineByName("State Machine 1", onChange: onStateChange)!);
  }
}

class BeachAnimations {
  final String waves = r"waves";
  final String idle = r"idle";
  final String load = r"load";
  final String shoot = r"shoot";
  final String boll = r"boll";
  final String boll2 = r"boll2";
  const BeachAnimations();
}

class BeachStateMachine1StateMachine {
  final rive.StateMachineController controller;
  final rive.SMITrigger charge;
  final rive.SMITrigger shoot;
  BeachStateMachine1StateMachine(this.controller)
      : charge = controller.findInput<bool>(r'charge') as rive.SMITrigger,
        shoot = controller.findInput<bool>(r'shoot') as rive.SMITrigger;
}

class Whale {
  final rive.Artboard artboard;
  Whale(this.artboard);

  final animations = const WhaleAnimations();
}

class WhaleAnimations {
  final String breathe = r"breathe";
  final String charge = r"charge";
  final String shoot = r"shoot";
  final String breatheold = r"breathe old";
  const WhaleAnimations();
}
